apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

bases:
- ../../../manifests/app/monitoring/jaeger/overlays/default
- ../../../manifests/app/monitoring/kafdrop/overlays/default
- ../../../manifests/app/monitoring/metrics/overlays/default
